export const DESELECT_TASKS = 'DESELECT_TASKS'
export const SELECTED_TASKS = 'SELECTED_TASKS'
export const SET_TASKS_FROM_ARRAY = 'SET_TASKS_FROM_ARRAY'
export const SET_ALL_TASKS = 'SET_ALL_TASKS'

export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'

export const SET_GROUPS = 'SET_GROUPS'
